version: '3.8'

services:
  # Static files init container
  static-files:
    build: .
    user: root
    command: ["sh", "-c", "cp -r /app/static /shared/ && chmod -R 755 /shared/static"]
    volumes:
      - static_files:/shared
    networks:
      - app-network

  # Data directory permissions fix
  data-permissions:
    build: .
    user: root
    command: ["sh", "-c", "chown -R 999:999 /app/data /app/logs && chmod -R 755 /app/data /app/logs"]
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - app-network

  # Nginx load balancer
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_files:/usr/share/nginx/html/static:ro
    depends_on:
      - static-files
    restart: unless-stopped
    networks:
      - app-network

  # FastAPI application (scalable)
  app:
    build: .
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_DEBUG=false
      - DATABASE_PATH=/app/data/memes.db
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-fallback_secret_key_change_in_production}
      - QR_CODE_URL=${QR_CODE_URL:-http://localhost:8081}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-4}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./static/memes:/app/static/memes:ro
    depends_on:
      - static-files
      - data-permissions
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/session/status"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 3

# Optional: SQLite Web UI for database management
  # Uncomment to enable web-based database access
  # sqliteweb:
  #   image: coleifer/sqlite-web
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./data:/data
  #   command: ["sqlite_web", "/data/memes.db", "--host", "0.0.0.0", "--port", "8080"]
  #   depends_on:
  #     - app
  #   networks:
  #     - app-network

volumes:
  static_files:

networks:
  app-network:
    driver: bridge
